### ISSUE TITLE
Docker Contextionary-Obsidian Errors

### ISSUE THREAD

**Issue by n810K** [echo-saurav/obsidian-ai-note-suggestion#5]
![CleanShot 2024-01-07 at 00 43 52@2x](https://github.com/echo-saurav/obsidian-ai-note-suggestion/assets/7424933/26aaf1af-ccb9-42a0-9089-d2c6180e2258)

I'm not sure whether this is a logging issue, or whether there is a problem. But functionality seems to be working fine in Obsidian regardless of the errors.

**Comment by n810K** [comment]
```
contextionary:
    container_name: contextionary-obsidian
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate-obsidian:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
    - 9999:9999
```

Changing EXTENSIONS_STORAGE_ORIGIN from http://weaviate:8080 to http://weaviate-obsidian:8080 has stopped the errors. 

There will still be error when starting up the first time as it needs to wait until Weaviate-Obsidian is fully running. But after that, there should be no more access issues. 
    
Please do some more testing to see if this fixes the issue. - PR: https://github.com/echo-saurav/obsidian-ai-note-suggestion/pull/6
