### ISSUE TITLE
Problem with weaver and NVDIA GPU

### ISSUE THREAD

**Issue by Lucas-Froguel** [echo-saurav/obsidian-ai-note-suggestion#8]
I could not use it at first with a NVDIA GPU, you have to install `nvidia-container-toolkit` and at the following lines to the docker compose file:
```
t2v-transformers-obsidian:
    container_name: t2v-transformers-obsidian
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    restart: unless-stopped
    environment:
      ENABLE_CUDA: '1'
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

Obs: this is not an issue, I just wanted to let you know without making a PR
